#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse


# Import from cjwpackage
import cjwpackage
from cjwpackage.lib import try_me

if __name__ == '__main__':
    try_me()
